# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nmfgen <- function(data, noSignatures, iter = 5000L) {
    .Call(`_NNMF_nmfgen`, data, noSignatures, iter)
}

nmftrain <- function(data, exposures, signatures, weight, iter = 5000L) {
    .Call(`_NNMF_nmftrain`, data, exposures, signatures, weight, iter)
}

nmfspatial <- function(data, noSignatures, weight, maxiter = 10000L, tolerance = 1e-8, initial = 100L, smallIter = 500L) {
    .Call(`_NNMF_nmfspatial`, data, noSignatures, weight, maxiter, tolerance, initial, smallIter)
}

nmfspatialbatch <- function(data, noSignatures, weight, batch, maxiter = 10000L, tolerance = 1e-8, initial = 10L, smallIter = 100L, error_freq = 10L) {
    .Call(`_NNMF_nmfspatialbatch`, data, noSignatures, weight, batch, maxiter, tolerance, initial, smallIter, error_freq)
}

nmfspatialbatch2 <- function(data, noSignatures, weight, batch, maxiter = 10000L, tolerance = 1e-8, error_freq = 10L) {
    .Call(`_NNMF_nmfspatialbatch2`, data, noSignatures, weight, batch, maxiter, tolerance, error_freq)
}

