# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nmfgen <- function(data, noSignatures, maxiter = 10000L, tolerance = 1e-8, initial = 10L, smallIter = 100L, error_freq = 10L) {
    .Call(`_NNMF_nmfgen`, data, noSignatures, maxiter, tolerance, initial, smallIter, error_freq)
}

nmfspatialbatch <- function(data, noSignatures, weight, batch, maxiter = 10000L, tolerance = 1e-8, initial = 10L, smallIter = 100L, error_freq = 10L) {
    .Call(`_NNMF_nmfspatialbatch`, data, noSignatures, weight, batch, maxiter, tolerance, initial, smallIter, error_freq)
}

nmfspatialbatch2 <- function(data, noSignatures, weight, batch, maxiter = 10000L, tolerance = 1e-8, error_freq = 10L) {
    .Call(`_NNMF_nmfspatialbatch2`, data, noSignatures, weight, batch, maxiter, tolerance, error_freq)
}

nmfspatial <- function(data, noSignatures, weight, maxiter = 10000L, tolerance = 1e-8, initial = 5L, smallIter = 100L, error_freq = 10L) {
    .Call(`_NNMF_nmfspatial`, data, noSignatures, weight, maxiter, tolerance, initial, smallIter, error_freq)
}

nmftrain <- function(data, exposures, signatures, sigma, ls_vec, maxiter = 5000L, tolerance = 1e-8, error_freq = 10L) {
    .Call(`_NNMF_nmftrain`, data, exposures, signatures, sigma, ls_vec, maxiter, tolerance, error_freq)
}

nmfgen_nb <- function(data, noSignatures, alpha, maxiter = 10000L, tolerance = 1e-8, initial = 10L, smallIter = 100L, error_freq = 10L) {
    .Call(`_NNMF_nmfgen_nb`, data, noSignatures, alpha, maxiter, tolerance, initial, smallIter, error_freq)
}

nmfspatialbatch_nb <- function(data, noSignatures, weight, batch, alpha, maxiter = 10000L, tolerance = 1e-8, initial = 10L, smallIter = 100L, error_freq = 10L) {
    .Call(`_NNMF_nmfspatialbatch_nb`, data, noSignatures, weight, batch, alpha, maxiter, tolerance, initial, smallIter, error_freq)
}

nmfspatialbatch2_nb <- function(data, noSignatures, weight, batch, alpha, maxiter = 10000L, tolerance = 1e-8, error_freq = 10L) {
    .Call(`_NNMF_nmfspatialbatch2_nb`, data, noSignatures, weight, batch, alpha, maxiter, tolerance, error_freq)
}

nmfspatial_nb <- function(data, noSignatures, weight, alpha, maxiter = 10000L, tolerance = 1e-8, initial = 5L, smallIter = 100L, error_freq = 10L) {
    .Call(`_NNMF_nmfspatial_nb`, data, noSignatures, weight, alpha, maxiter, tolerance, initial, smallIter, error_freq)
}

nmftrain_nb <- function(data, exposures, signatures, sigma, ls_vec, alpha, maxiter = 5000L, tolerance = 1e-8, error_freq = 10L) {
    .Call(`_NNMF_nmftrain_nb`, data, exposures, signatures, sigma, ls_vec, alpha, maxiter, tolerance, error_freq)
}

nmfgen_norm <- function(data, noSignatures, maxiter = 10000L, tolerance = 1e-8, initial = 10L, smallIter = 100L, error_freq = 10L) {
    .Call(`_NNMF_nmfgen_norm`, data, noSignatures, maxiter, tolerance, initial, smallIter, error_freq)
}

nmfspatialbatch_norm <- function(data, noSignatures, weight, batch, maxiter = 10000L, tolerance = 1e-8, initial = 10L, smallIter = 100L, error_freq = 10L) {
    .Call(`_NNMF_nmfspatialbatch_norm`, data, noSignatures, weight, batch, maxiter, tolerance, initial, smallIter, error_freq)
}

nmfspatialbatch2_norm <- function(data, noSignatures, weight, batch, maxiter = 10000L, tolerance = 1e-8, error_freq = 10L) {
    .Call(`_NNMF_nmfspatialbatch2_norm`, data, noSignatures, weight, batch, maxiter, tolerance, error_freq)
}

nmfspatial_norm <- function(data, noSignatures, weight, maxiter = 10000L, tolerance = 1e-8, initial = 5L, smallIter = 100L, error_freq = 10L) {
    .Call(`_NNMF_nmfspatial_norm`, data, noSignatures, weight, maxiter, tolerance, initial, smallIter, error_freq)
}

nmftrain_norm <- function(data, exposures, signatures, sigma, ls_vec, maxiter = 5000L, tolerance = 1e-8, error_freq = 10L) {
    .Call(`_NNMF_nmftrain_norm`, data, exposures, signatures, sigma, ls_vec, maxiter, tolerance, error_freq)
}

